name: Docker Image CI

on: push
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: kn2004-ppe:${{ github.sha }}
        outputs: type=docker, dest=/tmp/image.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: /tmp/image.tar

  push_to_registry:
    needs: build
    if: github.ref =='refs/heads/main'
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/image.tar
          docker images ls -a
        
      - name: Push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          
          docker tag kn2004-ppe:${{ github.sha }} 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2004-ecr-repo
          docker tag 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2004-ecr-repo kn2004-ppe:latest
          
          docker push kn2004-ppe:latest
