name: SAM Application Workflow
on: push
defaults:
  run:
    working-directory: ./kjell

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build SAM app
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v1
      - run: | 
          sam build /
          exit 0
          
  deploy:
    if: github.ref =='refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy SAM app
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      - run: |
          sam deploy --no-fail-on-empty-changeset --stack-name ${{ vars.DEPLOY_STACK_NAME }} --s3-bucket ${{ vars.DEPLOY_BUCKET_NAME }} \
          --region eu-west-1 --capabilities CAPABILITY_IAM --parameter-overrides "ParameterKey=ImageBucketName,ParameterValue=${{ vars.IMAGE_BUCKET_NAME }}" /
          exit 0
